ARG version
FROM almalinux:${version:-9}
# ekkada -: eche este user eme evanappudu danini default value la tesukuntundhi.
ARG course=docker
ARG trainer=sivakumar
ARG Duration=120hrs
ENV Duration=${Duration}
RUN echo "course is : ${course} , trainer is : ${trainer}", Duration is ${Duration}
CMD ["sleep", "100"]