ARG version
FROM almalinux:${version:-9}
# ekkada :- eche este user eme evanappudu danini default value la tesukuntundhi.
ARG ${course:-docker}
ARG ${trainer:-sivakumar}
RUN echo "course is : ${course} , trainer is : ${trainer}"
CMD ["sleep", "100"]